name: "pkgcheck"
description: "Test your package with {pkgcheck}."
branding:
  icon: 'check-circle'
  color: 'blue'
inputs:
  ref:
    description: "The ref to checkout and check. Set to empty string to skip checkout."
    default: "${{ github.ref }}"
    required: true
  path:
    description: "path within repo where package is located"
    default: "."
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      if: ${{ inputs.ref != ''}}
      uses: actions/checkout@v4
      with:
        ref: "${{ inputs.ref }}"
        fetch-depth: 0
    - name: "pkg-check"
      uses: ./.github/actions/core
      with:
        path: ${{ inputs.path }}
      id: pkgcheck
          
    - name: Fail if pkgcheck found problems
      run: exit ${{ steps.pkgcheck.outputs.status }}
      shell: bash
